name: panopto-data-api
channels:
  - anaconda
  - conda-forge
dependencies:
  - python-dotenv
  - python>= 3.7
  - zeep
  - pytz
  - pandas
  - urllib3
  - pip
  - pip:
      - requests
      - requests_oauthlib
