name: panopto-video-analytics
channels:
  - omnia
  - anaconda
  - conda-forge
dependencies:
  - python-dotenv
  - termcolor
  - python>= 3.7
  - zeep
  - pytz
  - pandas
  - urllib3
  - progress
  - colorama
  - pip
  - pip:
      - requests
      - requests_oauthlib
